import type { Metadata } from "next";
import {EB_Garamond, Montserrat, Cutive_Mono} from "next/font/google";
import "./globals.css";

const ebGaramond = EB_Garamond({
  subsets: ['latin'],
  variable: "--font-ebGaramond",
});
const montserrat = Montserrat({
  subsets: ['latin'],
  variable: "--font-montserrat",
});
const cutiveMono = Cutive_Mono({
  subsets: ['latin'],
  variable: "--font-cutiveMono",
  weight: '400'
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ebGaramond.variable} ${montserrat.variable} ${cutiveMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
